### PR TITLE
Allow Nette 3.0 stable

### PR DESCRIPTION
**Pull request by Gappa**
Relaxed composer.json to allow installation with `stable` minimum stability.

### CODE REVIEW

**Comment by paveljanda** [comment]
👍 thanks

**Comment by paveljanda** [comment]
Could you please fix the tests? Thx

**Comment by Gappa** [comment]
I should probably add that I tested it with the latest Nette Webproject :) 

Apart from some changes from previous versions (IMessageData, AbastractMail), I sent a few mails and it worked just fine.

**Comment by Gappa** [comment]
> Could you please fix the tests? Thx

Oh, I'll take a look.

**Comment by Gappa** [comment]
Uff, I got caught on a nasty bug: 

- https://github.com/nette/tester/issues/403

Otherwise just updated nette/tester & mockery.

**Comment by paveljanda** [comment]
Thank you. :)

**Comment by paveljanda** [comment]
https://github.com/ublaboo/mailing/releases/tag/v1.2.0

**Pull request merged**
